// Generated by scripts/generate-media-import-reports.mjs.
// Keep source media in media-source/assets and rerun the generator to refresh this file.
export const archiveStats = {
  "source": "milsim_rooster_simple_archive",
  "publicPath": "/media/archive/milsim/",
  "manifestPath": "media-source/assets/milsim_rooster_simple_archive/milsim_rooster_simple_archive/manifest.json",
  "sourceCount": 60,
  "selectedCount": 24,
  "excludedCategories": [
    "Video Clips",
    "Website Backgrounds",
    "AI & Cinematic Edits"
  ],
  "categoryCaps": {
    "Field Operations": 7,
    "Team & Community": 5,
    "Vehicles & Aircraft": 4,
    "Equipment & Details": 3,
    "Night Operations": 3,
    "CQB & Indoor": 2
  }
};

export const archiveItems = [
  {
    "title": "Two Characters Twinning",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/pirate-and-tactical-player-001.jpg",
    "caption": "",
    "archiveId": "MR-001",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor"
    ],
    "originalFilename": "Mall_CQB_Pirate_and_Tactical_Player.jpg"
  },
  {
    "title": "Rifleman Aiming From Cover",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/rifleman-aiming-from-cover-002.jpg",
    "caption": "",
    "archiveId": "MR-002",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor",
      "rifle"
    ],
    "originalFilename": "Mall_CQB_Rifleman_Aiming_From_Cover.jpg"
  },
  {
    "title": "Tossing a Frag",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/directional-command-003.jpg",
    "caption": "",
    "archiveId": "MR-003",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor"
    ],
    "originalFilename": "Mall_CQB_Directional_Command.jpg"
  },
  {
    "title": "Joker Pulling Rear Security",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/single-rifleman-security-004.jpg",
    "caption": "",
    "archiveId": "MR-004",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor",
      "rifle"
    ],
    "originalFilename": "Mall_CQB_Single_Rifleman_Security.jpg"
  },
  {
    "title": "Two Players Taking Aim at Their Targets",
    "category": "CQB & Indoor",
    "filter": "archive",
    "src": "/media/archive/milsim/two-riflemen-window-security-001.jpg",
    "caption": "",
    "archiveId": "MR-005",
    "collection": "CQB_and_Indoor",
    "assetCount": 2,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "cqb",
      "indoor",
      "rifle"
    ],
    "originalFilename": "Mall_CQB_Two_Riflemen_Window_Security.jpg"
  },
  {
    "title": "Bucees Statue Roadstop",
    "category": "Team & Community",
    "filter": "archive",
    "src": "/media/archive/milsim/bucees-statue-roadstop-001.jpg",
    "caption": "",
    "archiveId": "MR-006",
    "collection": "Team_and_Community",
    "assetCount": 16,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "team",
      "community"
    ],
    "originalFilename": "Stonebreaker_XII_Bucees_Statue_Roadstop.jpg"
  },
  {
    "title": "Airsoft With Friends",
    "category": "Team & Community",
    "filter": "archive",
    "src": "/media/archive/milsim/selfie-joker-002.jpg",
    "caption": "",
    "archiveId": "MR-007",
    "collection": "Team_and_Community",
    "assetCount": 16,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "team",
      "community"
    ],
    "originalFilename": "Stonebreaker_XII_GTI_Selfie_Joker.jpg"
  },
  {
    "title": "Soldier Peering Out to Acquire His Target",
    "category": "Team & Community",
    "filter": "archive",
    "src": "/media/archive/milsim/hawaiian-field-selfie-003.png",
    "caption": "",
    "archiveId": "MR-008",
    "collection": "Team_and_Community",
    "assetCount": 16,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "team",
      "community"
    ],
    "originalFilename": "Stonebreaker_XII_Rooster_Hawaiian_Field_Selfie.png"
  },
  {
    "title": "The Fupa at Operation Iron Fury",
    "category": "Vehicles & Aircraft",
    "filter": "archive",
    "src": "/media/archive/milsim/fish-club-interceptor-001.jpg",
    "caption": "",
    "archiveId": "MR-009",
    "collection": "Vehicles_and_Aircraft",
    "assetCount": 8,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "vehicle",
      "aircraft"
    ],
    "originalFilename": "Stonebreaker_XII_Fish_Club_Interceptor.jpg"
  },
  {
    "title": "Bucees Insurgent Camp",
    "category": "Team & Community",
    "filter": "archive",
    "src": "/media/archive/milsim/bucees-insurgent-camp-004.jpg",
    "caption": "",
    "archiveId": "MR-010",
    "collection": "Team_and_Community",
    "assetCount": 16,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "team",
      "community"
    ],
    "originalFilename": "Stonebreaker_XII_Bucees_Insurgent_Camp.jpg"
  },
  {
    "title": "Lakeside Truck Staging",
    "category": "Vehicles & Aircraft",
    "filter": "archive",
    "src": "/media/archive/milsim/lakeside-truck-staging-002.jpg",
    "caption": "",
    "archiveId": "MR-011",
    "collection": "Vehicles_and_Aircraft",
    "assetCount": 8,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "vehicle",
      "aircraft"
    ],
    "originalFilename": "Stonebreaker_XII_Lakeside_Truck_Staging.jpg"
  },
  {
    "title": "Milsim Marauders Having Fun at Operation Iron Fury",
    "category": "Equipment & Details",
    "filter": "archive",
    "src": "/media/archive/milsim/smiling-teammate-tactical-gear-001.jpg",
    "caption": "",
    "archiveId": "MR-012",
    "collection": "Equipment_and_Details",
    "assetCount": 6,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "gear",
      "equipment",
      "team"
    ],
    "originalFilename": "Stonebreaker_XII_Smiling_Teammate_Tactical_Gear.jpg"
  },
  {
    "title": "Lakeside Selfie With a Friend",
    "category": "Team & Community",
    "filter": "archive",
    "src": "/media/archive/milsim/lakeside-selfie-two-players-005.jpg",
    "caption": "",
    "archiveId": "MR-013",
    "collection": "Team_and_Community",
    "assetCount": 16,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "team",
      "community"
    ],
    "originalFilename": "Stonebreaker_XII_Lakeside_Selfie_Two_Players.jpg"
  },
  {
    "title": "Two Roosters",
    "category": "Equipment & Details",
    "filter": "archive",
    "src": "/media/archive/milsim/patches-002.jpg",
    "caption": "",
    "archiveId": "MR-014",
    "collection": "Equipment_and_Details",
    "assetCount": 6,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "gear",
      "equipment",
      "patch"
    ],
    "originalFilename": "Stonebreaker_XII_COMCAM_Rooster_Patches.jpg"
  },
  {
    "title": "Red Flare Night Field Moment",
    "category": "Night Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/red-flare-night-field-moment-001.png",
    "caption": "",
    "archiveId": "MR-015",
    "collection": "Night_Operations",
    "assetCount": 3,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "night",
      "low-light"
    ],
    "originalFilename": "Red_Flare_Night_Field_Moment.png"
  },
  {
    "title": "Woodland Fire Position Close",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/woodland-fire-position-close-005.jpg",
    "caption": "",
    "archiveId": "MR-016",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor"
    ],
    "originalFilename": "Woodland_Fire_Position_Close.jpg"
  },
  {
    "title": "Tier 1 Operation With the Goat Squad",
    "category": "Night Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/night-vision-goat-squad-interior-002.jpg",
    "caption": "",
    "archiveId": "MR-017",
    "collection": "Night_Operations",
    "assetCount": 3,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "night",
      "low-light",
      "goat"
    ],
    "originalFilename": "Night_Vision_Goat_Squad_Interior.jpg"
  },
  {
    "title": "Fiver Leading the Squad at Operation Bonecrusher",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/hilltop-two-player-firing-position-006.jpg",
    "caption": "",
    "archiveId": "MR-018",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor"
    ],
    "originalFilename": "Hilltop_Two_Player_Firing_Position.jpg"
  },
  {
    "title": "Soldier Taking Aim",
    "category": "Field Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/field-sniper-kneeling-overwatch-007.jpg",
    "caption": "",
    "archiveId": "MR-019",
    "collection": "Field_Operations",
    "assetCount": 18,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "field",
      "outdoor"
    ],
    "originalFilename": "Field_Sniper_Kneeling_Overwatch.jpg"
  },
  {
    "title": "After Game Selfie With Joker",
    "category": "Night Operations",
    "filter": "archive",
    "src": "/media/archive/milsim/night-vision-room-clearing-003.jpg",
    "caption": "",
    "archiveId": "MR-020",
    "collection": "Night_Operations",
    "assetCount": 3,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "night",
      "low-light"
    ],
    "originalFilename": "Night_Vision_Room_Clearing.jpg"
  },
  {
    "title": "MTW Unleashed",
    "category": "Vehicles & Aircraft",
    "filter": "archive",
    "src": "/media/archive/milsim/goat-mask-vehicle-portrait-003.jpg",
    "caption": "",
    "archiveId": "MR-021",
    "collection": "Vehicles_and_Aircraft",
    "assetCount": 8,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "vehicle",
      "aircraft",
      "portrait",
      "goat"
    ],
    "originalFilename": "Goat_Mask_Vehicle_Portrait.jpg"
  },
  {
    "title": "Pulling Security on the Objective",
    "category": "Equipment & Details",
    "filter": "archive",
    "src": "/media/archive/milsim/rifle-detail-rust-backdrop-003.jpg",
    "caption": "",
    "archiveId": "MR-022",
    "collection": "Equipment_and_Details",
    "assetCount": 6,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "gear",
      "equipment",
      "rifle"
    ],
    "originalFilename": "Rifle_Detail_Rust_Backdrop.jpg"
  },
  {
    "title": "M249 on a Hot Sunny Day",
    "category": "CQB & Indoor",
    "filter": "archive",
    "src": "/media/archive/milsim/m249-rifleman-window-position-002.jpg",
    "caption": "",
    "archiveId": "MR-023",
    "collection": "CQB_and_Indoor",
    "assetCount": 2,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "cqb",
      "indoor",
      "rifle"
    ],
    "originalFilename": "M249_Rifleman_Window_Position.jpg"
  },
  {
    "title": "Raffle Winner",
    "category": "Vehicles & Aircraft",
    "filter": "archive",
    "src": "/media/archive/milsim/doominator-gunner-flag-portrait-004.jpg",
    "caption": "",
    "archiveId": "MR-024",
    "collection": "Vehicles_and_Aircraft",
    "assetCount": 8,
    "tags": [
      "milsim",
      "airsoft",
      "event",
      "vehicle",
      "aircraft",
      "portrait"
    ],
    "originalFilename": "Doominator_Gunner_Flag_Portrait.jpg"
  }
];
